// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R5A08_TP1.Models.EntityFramework;

#nullable disable

namespace R5A08_TP1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905152509_ContrainteCleEnTropMigration3")]
    partial class ContrainteCleEnTropMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("marq_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("NomMarque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marq_nom");

                    b.HasKey("IdMarque")
                        .HasName("marque_pkey");

                    b.ToTable("t_e_marque_marq", "public");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("DescriptionProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prod_description");

                    b.Property<int?>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("marq_id");

                    b.Property<int?>("IdTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("typr_id");

                    b.Property<string>("NomPhotoProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prod_nomphoto");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prod_nomproduit");

                    b.Property<int>("StockMaxProduit")
                        .HasColumnType("integer")
                        .HasColumnName("prod_stockmax");

                    b.Property<int>("StockMinProduit")
                        .HasColumnType("integer")
                        .HasColumnName("prod_stockmin");

                    b.Property<int>("StockReelProduit")
                        .HasColumnType("integer")
                        .HasColumnName("prod_stockreel");

                    b.Property<string>("UriPhotoProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prod_uriphoto");

                    b.HasKey("IdProduit")
                        .HasName("produit_pkey");

                    b.HasIndex("IdMarque");

                    b.HasIndex("IdTypeProduit");

                    b.ToTable("t_e_produit_prod", "public");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.TypeProduit", b =>
                {
                    b.Property<int>("IdTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("typr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduit"));

                    b.Property<string>("NomMarque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typr_nom");

                    b.HasKey("IdTypeProduit")
                        .HasName("typeproduit_pkey");

                    b.ToTable("t_e_typeproduit_typr", "public");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Produit", b =>
                {
                    b.HasOne("R5A08_TP1.Models.EntityFramework.Marque", "MarqueNavigation")
                        .WithMany("ProduitsAssociesMarques")
                        .HasForeignKey("IdMarque")
                        .HasConstraintName("FK_produits_marque");

                    b.HasOne("R5A08_TP1.Models.EntityFramework.TypeProduit", "TypeProduitNavigation")
                        .WithMany("ProduitsAssociesTypesProduit")
                        .HasForeignKey("IdTypeProduit")
                        .HasConstraintName("FK_produits_type_produit");

                    b.Navigation("MarqueNavigation");

                    b.Navigation("TypeProduitNavigation");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Marque", b =>
                {
                    b.Navigation("ProduitsAssociesMarques");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.TypeProduit", b =>
                {
                    b.Navigation("ProduitsAssociesTypesProduit");
                });
#pragma warning restore 612, 618
        }
    }
}
